import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { TrendingUp, Calendar } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
export function PriceChart() {
    const mockData = [
        { date: "Nov 1", price: 7150 },
        { date: "Nov 2", price: 7180 },
        { date: "Nov 3", price: 7200 },
    ];
    const maxPrice = Math.max(...mockData.map((d) => d.price));
    const minPrice = Math.min(...mockData.map((d) => d.price));
    const range = maxPrice - minPrice;
    return (_jsxs(motion.section, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, viewport: { once: true }, className: "container mx-auto px-4 py-20", children: [_jsxs("div", { className: "text-center mb-12", children: [_jsxs("div", { className: "inline-flex items-center space-x-2 bg-yellow-100 dark:bg-yellow-900/30 px-4 py-2 rounded-full mb-4", children: [_jsx(TrendingUp, { className: "h-5 w-5 text-yellow-700 dark:text-yellow-400" }), _jsx("span", { className: "text-sm font-medium text-yellow-800 dark:text-yellow-300", children: "Price Trends" })] }), _jsx("h2", { className: "text-4xl font-bold mb-4", children: "Gold Price Trends" }), _jsx("p", { className: "text-muted-foreground max-w-2xl mx-auto", children: "Track historical gold price movements over time" })] }), _jsxs(Card, { className: "max-w-4xl mx-auto shadow-lg", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "24K Gold Price Movement" }), _jsx(CardDescription, { children: "Last 3 days trend (per gram)" })] }), _jsxs(CardContent, { children: [_jsx("div", { className: "h-64 flex items-end space-x-4", children: mockData.map((data, index) => {
                                    const heightPercent = range > 0 ? ((data.price - minPrice) / range) * 100 : 50;
                                    return (_jsxs(motion.div, { initial: { height: 0 }, animate: { height: `${heightPercent}%` }, transition: { duration: 0.5, delay: index * 0.1 }, className: "flex-1 flex flex-col items-center", children: [_jsx("div", { className: "w-full bg-gradient-to-t from-yellow-400 to-yellow-600 rounded-t-lg relative group cursor-pointer hover:from-yellow-500 hover:to-yellow-700 transition-colors", children: _jsxs("div", { className: "absolute -top-8 left-1/2 transform -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity bg-gray-900 text-white text-xs px-2 py-1 rounded whitespace-nowrap", children: ["\u20B9", data.price.toLocaleString()] }) }), _jsx("div", { className: "mt-4 text-sm text-muted-foreground", children: data.date })] }, index));
                                }) }), _jsx("div", { className: "mt-8 p-4 bg-muted/50 rounded-lg", children: _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Calendar, { className: "h-4 w-4 text-muted-foreground" }), _jsx("span", { className: "text-muted-foreground", children: "Period: Last 3 days" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { children: [_jsx("span", { className: "text-muted-foreground", children: "High: " }), _jsxs("span", { className: "font-semibold text-green-600", children: ["\u20B9", maxPrice.toLocaleString()] })] }), _jsxs("div", { children: [_jsx("span", { className: "text-muted-foreground", children: "Low: " }), _jsxs("span", { className: "font-semibold text-red-600", children: ["\u20B9", minPrice.toLocaleString()] })] })] })] }) })] })] })] }));
}
